<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="TestService"
     targetNamespace="http://xmlns.oracle.com/TestParallel/TestParallel/TestService"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/TestParallel/TestParallel/TestService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="TestService">
        <plnk:role name="TestServiceProvider">
            <plnk:portType name="client:TestService"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/TestParallel/TestParallel/TestService" schemaLocation="xsd/TestService.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="TestServiceRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="TestServiceResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="TestService">
        <wsdl:operation name="process">
            <wsdl:input message="client:TestServiceRequestMessage"/>
            <wsdl:output message="client:TestServiceResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
